version: '3.8'

services:
  subtitle-generator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    runtime: nvidia  # This specifies that the NVIDIA runtime should be used